name: Weekly DB Backup

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Run backup script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bash scripts/backup-db.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup-${{ github.run_number }}
          path: backups/
      # - name: Upload to S3 (futuro)
      #   run: echo 'Integrar com S3'